#+title: Н. Зайцев, Путь 1С-разработки
#+author: Centrix
* Заметки и вопросы
** Глава 1. Выстраиваем концепцию
*** Краткий курс политэкономии
Автор противопоставляет два способа разработки ПО:
1) быстро и криво,
2) не спеша, эффективно и правильно.

Для первого способа он описывает характерные признаки, а для второго — достоинства и недостатки.

**** Закон сохранения стоимости
Но дело не в самом существовании этих подходов, а в том, что выбирать между ними не приходится. Это продиктовано /законом сохранения стоимости/.

Всякая задача разработки, – утверждает автор, – представляет собой чью-то проблему. Эту проблему стараются решить потому, что она приносит убыток. Соответственно, чем больше убыток, чем больше труда вмещает в себя проблема, тем дороже будет разработка. Стоимость решения проблемы равна стоимости самой проблемы.

Эта мысль обладает двумя характерными чертами.

Во-первых, она весьма проста и понятна. Благодаря ней /требование/ «нормальной разработки» превращается в /необходимость/. Правильная разработка — это не предпочтение, а объективная закономерность, которую можно избегать, но нельзя отменить или сгладить.

Во-вторых, она яснее ставит вопрос: «а в чём же тогда цель автоматизации?» Если разработка ПО равноценна по стоимости проблеме, ради которой предпринимается, то, следовательно, дело не в экономии ресурсов.

Дело в том, что разработка позволяет /перераспределить/ ресурсы и силы, но не изменяет их /суммарного объёма/. Экономия от автоматизации — это видимость, чисто психологический эффект.

Так, в общих чертах, можно сформулировать и раскрыть «закон сохранения стоимости».
#+begin_comment
Удивительно, но всё сказанное приходится добывать самому, прямо-таки клещами вытаскивать из текста. Почему автор не тратит на это времени?
#+end_comment

**** Парадокс убыточного удешевления
Но выстроенная ранее дихотомия интересна не только этим. Автор считает, что в «живых» проектах закон сохранения стоимости имеет только нижнюю планку и потому может быть сформулирован так.

Разработка по принципу «быстро и криво» обходится /не дешевле/ разработки по принципу «не спеша, эффективно и правильно». Часто бывает так, что проекты написанные криво даже дороже тех, которые сделаны правильно.

#+begin_comment
Правда, это не согласуется с законом сохранения стоимости. Правильнее было бы сказать, что разработка обоими способами в стоимостном выражении эквивалентна, но различным образом распределена во времени.

Экономия на разработке делает дорогой эксплуатацию. Экономия на эксплуатации делает дорогой разработку.

Разницы с /суммах/ здесь нет, но различие в распределении усилий, различие качества этих самых усилий создаёт психологический эффект различия общей стоимости.
#+end_comment

*** Собеседование в трёх гримасах
Если в предыдущем параграфе автор исследовал общие свойства разработки ПО, то теперь он переходит к частным. Частные стороны разработки он рассматривает в связи с профессией разработчика ПО.

**** Ремесло или творчество?
Первый вопрос, которого касается автор, заключается в характере разработки ПО и соответствующего специалиста.

Автор считает, что программирование и разработка — это две несколько различных области. Разработка — это одни из сфер программирования, и программирование, поэтому, не исчерпывается разработкой.

По этой причине автор далее разделяет понятия «программист» и «разработчик». Чёткого определения эти понятия не получают, но для них выведено ключевое различие: работа программиста творческая, а вот разработка — чистое ремесло.
#+begin_comment
Сама попытка решить вопрос заслуживает большого уважения. Не так много авторов интересуются характером своей работы и решают этот вопрос хоть сколько-нибудь обоснованно.

Но мнение Н. Зайцева принять трудно. Различение творчества и ремесла весьма эфемерно, оно существует лишь постольку, поскольку под ремеслом понимается узкая, исключительно практическая, — мышиная работа. Но ведь решение рабочих задач очень часто выходит за рамки мышиной работы. Ремесло может переходить в творчество, а творчество — в ремесло (и это переход весьма печальный). Куда более продуктивным было бы рассмотрение этого перехода и обозначение /тенденции/, а не /стороны/.
#+end_comment

**** Олимпиада или производство?
Второй вопрос тесно связан с первым. Как должна вестись разработка, какими темпами, для каких целей?

Есть два ответа на этот вопрос: (1) олимпийство: разработка — это спорт, её нужно вести быстро, в соревновательном духе, она должна быть самоцелью; (2) производство: разработка — это один из аспектов реального производства, его обеспечивающая сторона, разработка должна быть постепенной и качественной, соразмерной производству, цель разработки — удовлетворение нужд производства.

И, конечно, автор занимает вторую точку зрения: разработка ПО — это производство. Здесь нет места рекордам, геройству, овациям и т. д.
#+begin_comment
Снова та же ошибка: вместо конструирования дихотомии познание должно эту дихотомию устранять, его задача не в том, чтобы постулировать видимость, а в том, чтобы выяснить её сущность, понять переход одной стороны в другую.

Усердие в «производственном» характере разработки ни к чему хорошему не ведёт.
#+end_comment

**** Техническое задание или технический проект?
Наконец, третий вопрос (и, конечно, третья дихотомия): что должно служить источником разработки — техническое задание (ТЗ) или технический проект (ТП)?

Автор считает, что исчерпывающее и полное ТЗ — большая редкость, исключение, но не правило. Изменчивость и сложность задач заказчиков делают создание настоящего ТЗ почти невозможным и бесполезным. Поэтому в реальной разработке речь идёт о технических проектах, в которых формулируется проблема, исходные условия и стратегия разработки. Тактика же отыскивается в ходе взаимодействия разработчика и заказчика.

Но полнота — не единственное различие ТЗ и ТП. Второе, можно сказать — ключевое, заключается в том, что ТЗ для разработчика — исключительно внешняя сущность, он не имеет к ней отношения. ТП же — это плод совместной работы разработчика (команды разработчиков) и заказчика, в ТП отражаются особенности разработчика, его причастность к своей работе.

*** Три простых способа всё испортить
Продолжая рассмотрение разработки, автор переходит к вопросам организации. В этом параграфе он будет говорить о:
- геймификации,
- штурмовщине,
- agile.

**** Как превратить работу в детский утренник (геймификация)
Один из способов нефинансовой мотивации сотрудников — это геймификация. Автор считает, что ничего хорошего она не принесёт. В лучшем случае она просто не будет работать (разработчикам будут не интересны призы), а в худшем — создаст нездоровые стимулы, из-за которых начнутся приписки, борьба за количество против качества и т. д.

В качестве альтернативы автор предлагает финансовую мотивацию (премии) и антимотивацию (наказания за низкое качество работы).

**** Как превратить работу в штурм крепости (штурмовщина)
Вторая вредная, по мнению автора, практика — это штурмовщина. Штурмовщина предполагает быстрое, ураганное решение задач, штурм их. Задача при таком подходе рассматривается, как противник, которого нужно уничтожить.

Штурмовщина может принимать форму хакатонов, в ходе которых за несколько дней создаётся частичное решение конкретной задачи. Такой подход близок к современной MVP-разработке, в которой вместо проектирования сначала создаётся частичное (как выразился бы автор: кривое) решение, а уже потом на его опыте — полноценное.

Автор, как этого следовало ожидать, предпочитает штурмовщине неспешную, правильную разработку.

**** Как согнуть работу в бараний рог (Agile)
Автор не выступает против методик Agile, но он обращает внимание читателя на то, что у них есть границы применения. Невозможно соединение agile с гибким рабочим графиком или плавающими сроками, невозможен нормальный анализ (ретроспектива), когда задачи ставятся «с колёс». Кроме того, весьма вредны постоянные обновления.

Это были лишь конкретные примеры, они позволяют понять, что гибкие методики — не панацея, их нужно применять разумно и не смешивать с тем, что с ними несовместимо.

** Глава 2. Формализуем теорию
Эта глава, как и следует из её названия, посвящена теоретическим положениям, которые автору кажутся наиболее существенными. Теория здесь не принимает вида, собственно, теории: в ней нет системы; она представляет собой скорее азбуку, свод советов, но не теорию.

*** Светлая сторона Силы
**** DRY/DIE
Первый наиболее важный принцип — это принцип не повторяться (DRY, альтернативная формулировка: DIE — Duplication Is Evil).

Автор уместно замечает (хотя неуместно здесь высказаться трудно), что копирование кода — ложный путь, вместо повторения необходимо абстрагировать или отделить выделить логику. Однако заключение этой мысли выходит очень странным:
#+begin_quote
Копирование — зло. Не копируйте, пишите. Руки не отвалятся.
#+end_quote

Можно различным образом истолковать такую неподходящую лаконичность, и один из способов состоит в том, что нужно не копировать, а переписывать код. Это заключение ложно. Странно, что автор допускает такое.

**** GIGO
Второй принцип также получает туманную формулировку: Garbage In — Garbage Out (мусор на входе — мусор на выходе). Из названия следует, что принцип отражает одно неприятное свойство алгоритмов: они могут возвращать некорректные значения при некорректных входных данных. Но из этого совершенно не ясно, в чём же состоит /принцип/.

А состоит он в том, что разработчик должен заботиться о валидации данных. Программа не должна позволить пользователю ввести заведомо ложные данные.

**** KISS
Суть этого принципа так же ясна и понятна: необходимо искать простые и ясные решения. Такие решения, пусть и просты, всё же понятны и надёжны, а эти качества заказчики ценят больше всего.

#+begin_comment
Трудно не согласиться с тем, что простота — цель, к которой нужно стремиться. Но возмущает то, как авторы книг говорят о простоте. Их интересует только формулировка принципа, но не гораздо более важный и сложный вопрос: «а что такое простота?»

Действительно: при реализации системы геометрического моделирования весьма простым кажется хранить типы и координаты объектов (например, точку и её координаты, отрезок и две точки и т. д.).

Однако эта простота со временем играет злую шутку: оказывается, что для хоть сколько-нибудь более сложных задач, чем отображение, требуется гораздо больше информации: нужно хранить коэффициенты уравнения, описывающего данный объект. Но разве это просто?
#+end_comment

**** YAGNI
Принцип YAGNI продолжает KISS, он гласит, что многие возможности заказчику не нужны. И поэтому прежде чем браться за реализацию чего-либо, необходимо сначала разобраться в том, какую производственную задачу (или проблему) разработка решает. Если производству возможность не нужна, то реализовать её — сомнительная идея.

#+begin_comment
С этим принципом автор, правда, снова попадает в ловушку. Применение некоторой функции, использование её, возможно только тогда, когда эта функция есть. Без возможности не будет действительности. И потому возведение «гранитной стены» (авторское выражение) принципа YAGNI чревато превращением разработки из проактивной (идущей в ногу с производством) в реактивную (идущей в хвосте производства).

Именно поэтому опять же простой формулировки принципа недостаточно, необходимо исследовать вопрос глубже.
#+end_comment

**** LIAR
Последнему принципу автор для стилистической однородности тоже даёт звучную латинскую аббревиатуру. Только скрывается за этой аббревиатурой до боли знакомое «Работает — не трогай». Пояснять суть, а уж тем более глубокую противоречивость этого принципа будет излишним.

*** Тёмная сторона силы
Описывать этот раздел совершенно бессмысленно: автор приводит в нём различные «вредные советы» по написанию кода. Рассказывается о разных стилях — индусский, китайский, крестьянский, — и т. д.

Отметить разве что можно рассмотрение оверинжиниринга и сверхвариативности.

*** Слагаемые эффективной разработки
В последнем параграфе главы автор рассматривает стадии разработки ПО. Он выделяет:
1) планирование,
2) проектирование,
3) прототипирование (требуется не всегда),
4) отладка,
5) тестирование,
6) комментирование,
7) документирование,
8) сопровождение и оптимизация.

**** Планирование
Можно выделить два типических способа планирования:
1) детерминистский (академический),
2) индетерминистский (производственный).

Детерминистский подход предполагает полную определённость и ясность задачи, а потому и создание исчерпывающего плана.

Индетерминистский подход предполагает меньшую определённость входных данных и потому концентрируется на том, чтобы планировать только известное, делая скидку на неопределённость условий.

Иллюстрировать детерминистский подход не требуется: все современные студенты компьютерных специальностей прекрасно «знают» как «планировать» свою работу при помощи целей, задач и Microsoft Project.

Второй подход интереснее. Он, как и первый, предполагает разбиение большой задачи на меньшие, но само это разбиение выполняется ограничено, без надежды на то, чтобы раскрошить задачу на атомы.

Например, ставится задача: организовать выгрузку данных из системы X в систему Y. Инженер вместо того, чтобы ожидать исчерпывающего задания начнёт собственное исследование: какими средствами интеграции системы уже обладают, каковы ограничения этих средств, возможно ли применение новых средств и для каких задач и т. д. Лишь исчерпав границы известного, он обратится за новыми разъяснениями.

**** Проектирование
Автор заранее говорит, что сейчас из этой темы возьмёт только один аспект: формы проектирования.

Необходимо различать проектирование для разработчика и проектирование для заказчика. Проектирование для заказчика предполагает создание некоторой документации: пользовательской, отчётов, диаграмм и т. д. Эта документация необходима для взаимодействия с заказчиком и координации разработки.

Совсем другое дело проектирование для разработчика. Разработчик проектирует систему в понятных ему понятиях, он составляет различные диаграммы, схемы и описания, но не для того, чтобы их читал заказчик, а чтобы работать по ним над системой. Результаты проектирования для разработчика представляют собой, в каком-то смысле, «записки сумашедшего», в которых описан ход и цель мысли, проблемы и решения. Такая документация служит самому разработчику и его потомкам.

**** Отладка
В отличие от предыдущих стадий, стадии конструирования (кодирования), отладки и исправления ошибок дают возможность /численно/ оценить качество работы. Автор приводит три профиля загрузки специалиста.

| Профиль    |  I | II | III |
|------------+----+----+-----|
| Низкий     | 20 | 80 |   0 |
| Средний    | 33 | 34 |  33 |
| Нормальный | 80 | 10 |  10 |

В таблице приняты следующие обозначения: I — доля трудозатрат на конструирование, II — на отладку, III — на исправление ошибок.

Первый профиль (низкий) описывает запредельно низкое качество работы. Код пишется быстро и почти бездумно, много времени уходит на отладку и почти полную переделку исходной реализации; нормальное тестирование почти не выполняется.

Второй профиль (средний) описывает невысокое качество работы. Наконец, нормальный профиль описывает разработку такой, какой её видит автор: большая часть времени уходит на качественное конструирование, а на этапах отладки и исправления идёт шлифовка системы.

**** Тестирование
В тестировании можно выделить два крайних подхода.

Первый заключается в том, что разрабатывает разработчик, а тестирует тестировщик. Между ними возводится нерушимая стена, функции полностью разделяются. Ясно, что ни к чему, кроме низкого качества кода такое не приводит.

Второй подход заключается в том, что разработчик покрывает тестами весь код (TDD) и уже только после того, как работа полностью завершена, передаёт свою работу на тестирование.
#+begin_comment
Нужно однако заметить, что суть TDD не в этом. Речь в TDD о примате вычислимой спецификации кода над самим кодом. Роль такой спецификации могут играть тесты, а могут — иные инструменты.
#+end_comment

Автор считает TDD полезной, но чересчур дорогой технологией, поэтому считает, что действовать нужно по ситуации.

**** Комментирование
Ровно также, как и в тестировании, в комментировании необходимо соблюдать меру. Совершенно неуместны комментарии, пересказывающие код. Но комментарии, поясняющие суть работы кода, его мотивацию необходимы жизненно.

При этом важно отметить, что сведения, приведённые в данном пункте, противоречат тому, что говорит автор далее — в пункте «Правило обязательной полезной аннотации» (гл. 3). Если здесь он настаивает на том, чтобы ненужные комментарии опускать, то далее приведёт пример пустой аннотации:
#+begin_example
  // Аннотация не требуется, см. имя метода.
  // …
#+end_example

Зачем засорять код такой ерундой — неясно (к тому же, автор призывает сохранить этот кусочек для повсеместного копирования). Вместо этого можно оставлять пустой комментарий (=//=), суть не изменится.

**** Документирование
Никакого отдельного документирования кода не требуется: всё необходимое разработчик уже создал на этапе проектирования и конструирования.
