#+title: Н. Зайцев, Путь 1С-разработки
#+author: Centrix
* Заметки и вопросы
** Глава 1. Выстраиваем концепцию
*** Краткий курс политэкономии
Автор противопоставляет два способа разработки ПО:
1) быстро и криво,
2) не спеша, эффективно и правильно.

Для первого способа он описывает характерные признаки, а для второго — достоинства и недостатки.

**** Закон сохранения стоимости
Но дело не в самом существовании этих подходов, а в том, что выбирать между ними не приходится. Это продиктовано /законом сохранения стоимости/.

Всякая задача разработки, – утверждает автор, – представляет собой чью-то проблему. Эту проблему стараются решить потому, что она приносит убыток. Соответственно, чем больше убыток, чем больше труда вмещает в себя проблема, тем дороже будет разработка. Стоимость решения проблемы равна стоимости самой проблемы.

Другими словами, разработка отнимает столько же общественно-необходимого рабочего времени, сколько и выполнение деятельности. Стоимость сохраняется. Эффект от автоматизации достигается тем, что когда разработка завершается, она позволяет перераспределить рабочее время: отвести его от проблемы в другие места. Это и есть /закон сохранения стоимости/.

Таким образом, выбор второго пути разработки — это не субъективный выбор, а объективная необходимость. Можно не обращать на эту необходимость внимания, но в таком случае в один момент всю работу придётся начать сначала, тем самым восстановив равенство.

Именно поэтому в каких-то проектах на проектировании и документировании удаётся сэкономить, а в других — нет. Дело здесь в /экономике/.

**** Парадокс убыточного удешевления
Но выстроенная ранее дихотомия интересна не только этим. Автор считает, что в «живых» проектах закон сохранения стоимости имеет только нижнюю планку и потому может быть сформулирован так:

Разработка по принципу «быстро и криво» обходится /не дешевле/ разработки по принципу «не спеша, эффективно и правильно». Часто бывает так, что проекты написанные криво даже дороже тех, которые сделаны правильно.

#+begin_comment
Правда это не согласуется с законом сохранения стоимости. Правильнее было бы сказать, что разработка обоими способами в стоимостном выражении эквивалентна, но различным образом распределена во времени.

Экономия на разработке делает дорогой эксплуатацию. Экономия на эксплуатации делает дорогой разработку.

При этом дорогая разработка и дешёвая эксплуатация /психологически/ ощущается дешевле первого варианта.
#+end_comment
