#+title: Н. Зайцев, Путь 1С-разработки
#+author: Centrix
* Заметки и вопросы
** Глава 1. Выстраиваем концепцию
*** Краткий курс политэкономии
Автор противопоставляет два способа разработки ПО:
1) быстро и криво,
2) не спеша, эффективно и правильно.

Для первого способа он описывает характерные признаки, а для второго — достоинства и недостатки.

**** Закон сохранения стоимости
Но дело не в самом существовании этих подходов, а в том, что выбирать между ними не приходится. Это продиктовано /законом сохранения стоимости/.

Всякая задача разработки, – утверждает автор, – представляет собой чью-то проблему. Эту проблему стараются решить потому, что она приносит убыток. Соответственно, чем больше убыток, чем больше труда вмещает в себя проблема, тем дороже будет разработка. Стоимость решения проблемы равна стоимости самой проблемы.

Эта мысль обладает двумя характерными чертами.

Во-первых, она весьма проста и понятна. Благодаря ней /требование/ «нормальной разработки» превращается в /необходимость/. Правильная разработка — это не предпочтение, а объективная закономерность, которую можно избегать, но нельзя отменить или сгладить.

Во-вторых, она яснее ставит вопрос: «а в чём же тогда цель автоматизации?» Если разработка ПО равноценна по стоимости проблеме, ради которой предпринимается, то, следовательно, дело не в экономии ресурсов.

Дело в том, что разработка позволяет /перераспределить/ ресурсы и силы, но не изменяет их /суммарного объёма/. Экономия от автоматизации — это видимость, чисто психологический эффект.

Так, в общих чертах, можно сформулировать и раскрыть «закон сохранения стоимости».
#+begin_comment
Удивительно, но всё сказанное приходится добывать самому, прямо-таки клещами вытаскивать из текста. Почему автор не тратит на это времени?
#+end_comment

**** Парадокс убыточного удешевления
Но выстроенная ранее дихотомия интересна не только этим. Автор считает, что в «живых» проектах закон сохранения стоимости имеет только нижнюю планку и потому может быть сформулирован так.

Разработка по принципу «быстро и криво» обходится /не дешевле/ разработки по принципу «не спеша, эффективно и правильно». Часто бывает так, что проекты написанные криво даже дороже тех, которые сделаны правильно.

#+begin_comment
Правда, это не согласуется с законом сохранения стоимости. Правильнее было бы сказать, что разработка обоими способами в стоимостном выражении эквивалентна, но различным образом распределена во времени.

Экономия на разработке делает дорогой эксплуатацию. Экономия на эксплуатации делает дорогой разработку.

Разницы с /суммах/ здесь нет, но различие в распределении усилий, различие качества этих самых усилий создаёт психологический эффект различия общей стоимости.
#+end_comment

*** Собеседование в трёх гримасах
Если в предыдущем параграфе автор исследовал общие свойства разработки ПО, то теперь он переходит к частным. Частные стороны разработки он рассматривает в связи с профессией разработчика ПО.

**** Ремесло или творчество?
Первый вопрос, которого касается автор, заключается в характере разработки ПО и соответствующего специалиста.

Автор считает, что программирование и разработка — это две несколько различных области. Разработка — это одни из сфер программирования, и программирование, поэтому, не исчерпывается разработкой.

По этой причине автор далее разделяет понятия «программист» и «разработчик». Чёткого определения эти понятия не получают, но для них выведено ключевое различие: работа программиста творческая, а вот разработка — чистое ремесло.
#+begin_comment
Сама попытка решить вопрос заслуживает большого уважения. Не так много авторов интересуются характером своей работы и решают этот вопрос хоть сколько-нибудь обоснованно.

Но мнение Н. Зайцева принять трудно. Различение творчества и ремесла весьма эфемерно, оно существует лишь постольку, поскольку под ремеслом понимается узкая, исключительно практическая, — мышиная работа. Но ведь решение рабочих задач очень часто выходит за рамки мышиной работы. Ремесло может переходить в творчество, а творчество — в ремесло (и это переход весьма печальный). Куда более продуктивным было бы рассмотрение этого перехода и обозначение /тенденции/, а не /стороны/.
#+end_comment

**** Олимпиада или производство?
Второй вопрос тесно связан с первым. Как должна вестись разработка, какими темпами, для каких целей?

Есть два ответа на этот вопрос: (1) олимпийство: разработка — это спорт, её нужно вести быстро, в соревновательном духе, она должна быть самоцелью; (2) производство: разработка — это один из аспектов реального производства, его обеспечивающая сторона, разработка должна быть постепенной и качественной, соразмерной производству, цель разработки — удовлетворение нужд производства.

И, конечно, автор занимает вторую точку зрения: разработка ПО — это производство. Здесь нет места рекордам, геройству, овациям и т. д.
#+begin_comment
Снова та же ошибка: вместо конструирования дихотомии познание должно эту дихотомию устранять, его задача не в том, чтобы постулировать видимость, а в том, чтобы выяснить её сущность, понять переход одной стороны в другую.

Усердие в «производственном» характере разработки ни к чему хорошему не ведёт.
#+end_comment

**** Техническое задание или технический проект?
Наконец, третий вопрос (и, конечно, третья дихотомия): что должно служить источником разработки — техническое задание (ТЗ) или технический проект (ТП)?

Автор считает, что исчерпывающее и полное ТЗ — большая редкость, исключение, но не правило. Изменчивость и сложность задач заказчиков делают создание настоящего ТЗ почти невозможным и бесполезным. Поэтому в реальной разработке речь идёт о технических проектах, в которых формулируется проблема, исходные условия и стратегия разработки. Тактика же отыскивается в ходе взаимодействия разработчика и заказчика.

Но полнота — не единственное различие ТЗ и ТП. Второе, можно сказать — ключевое, заключается в том, что ТЗ для разработчика — исключительно внешняя сущность, он не имеет к ней отношения. ТП же — это плод совместной работы разработчика (команды разработчиков) и заказчика, в ТП отражаются особенности разработчика, его причастность к своей работе.
