#+title: Н. Зайцев, Путь 1С-разработки
#+author: Centrix
* Заметки и вопросы
** Глава 1. Выстраиваем концепцию
*** Краткий курс политэкономии
Автор противопоставляет два способа разработки ПО:
1) быстро и криво,
2) не спеша, эффективно и правильно.

Для первого способа он описывает характерные признаки, а для второго — достоинства и недостатки.

**** Закон сохранения стоимости
Но дело не в самом существовании этих подходов, а в том, что выбирать между ними не приходится. Это продиктовано /законом сохранения стоимости/.

Всякая задача разработки, – утверждает автор, – представляет собой чью-то проблему. Эту проблему стараются решить потому, что она приносит убыток. Соответственно, чем больше убыток, чем больше труда вмещает в себя проблема, тем дороже будет разработка. Стоимость решения проблемы равна стоимости самой проблемы.

Эта мысль обладает двумя характерными чертами.

Во-первых, она весьма проста и понятна. Благодаря ней /требование/ «нормальной разработки» превращается в /необходимость/. Правильная разработка — это не предпочтение, а объективная закономерность, которую можно избегать, но нельзя отменить или сгладить.

Во-вторых, она яснее ставит вопрос: «а в чём же тогда цель автоматизации?» Если разработка ПО равноценна по стоимости проблеме, ради которой предпринимается, то, следовательно, дело не в экономии ресурсов.

Дело в том, что разработка позволяет /перераспределить/ ресурсы и силы, но не изменяет их /суммарного объёма/. Экономия от автоматизации — это видимость, чисто психологический эффект.

Так, в общих чертах, можно сформулировать и раскрыть «закон сохранения стоимости».
#+begin_comment
Удивительно, но всё сказанное приходится добывать самому, прямо-таки клещами вытаскивать из текста. Почему автор не тратит на это времени?
#+end_comment

**** Парадокс убыточного удешевления
Но выстроенная ранее дихотомия интересна не только этим. Автор считает, что в «живых» проектах закон сохранения стоимости имеет только нижнюю планку и потому может быть сформулирован так.

Разработка по принципу «быстро и криво» обходится /не дешевле/ разработки по принципу «не спеша, эффективно и правильно». Часто бывает так, что проекты написанные криво даже дороже тех, которые сделаны правильно.

#+begin_comment
Правда, это не согласуется с законом сохранения стоимости. Правильнее было бы сказать, что разработка обоими способами в стоимостном выражении эквивалентна, но различным образом распределена во времени.

Экономия на разработке делает дорогой эксплуатацию. Экономия на эксплуатации делает дорогой разработку.

Разницы с /суммах/ здесь нет, но различие в распределении усилий, различие качества этих самых усилий создаёт психологический эффект различия общей стоимости.
#+end_comment
